// ====================================
// 线索审核模块 - 独立数据文件
// Clue Review Module - Isolated Data File
// ====================================
// 此文件仅供线索审核模块使用
// 修改此文件不会影响其他模块

import type { Clue } from "@/lib/modules/clue-review/types"

// 线索审核页面的筛选选项
export const clueReviewChannelOptions = ["Telegram", "Discord", "暗网论坛", "微信群", "QQ群", "Twitter", "其他"]

export const clueReviewRiskSceneOptions = [
  "账号盗用",
  "虚假交易",
  "提供礼品卡交易服务",
  "信息窃取",
  "资金盗取",
  "身份冒用",
  "其他",
]

export const clueReviewRiskTagOptions = [
  "银行卡买卖",
  "四件套",
  "身份信息泄露",
  "刷单",
  "虚假交易",
  "佣金诈骗",
  "信用卡盗刷",
  "CVV交易",
  "数据泄露",
  "保险欺诈",
  "虚假理赔",
  "骗保",
  "内部数据",
  "客户信息",
  "数据买卖",
  "荐股诈骗",
  "投资诈骗",
  "贷款诈骗",
  "虚假广告",
  "非法金融",
  "非法支付通道",
  "发票造假",
  "对公账户买卖",
]

export const clueReviewCustomerOptions = [
  "AMAZON",
  "TIKTOKSHOP",
  "TIKTOK",
  "SHEIN",
  "ICBU",
  "ALIEXPRESS",
  "LAZADA",
  "VINTED",
]

// 线索审核模块的模拟数据
export const clueReviewMockClues: Clue[] = [
  {
    id: "CLU-2024122501",
    captureTime: "2024-12-25 08:32:15",
    customer: "AMAZON",
    industry: "电商",
    original:
      "出售银行卡四件套，身份证+银行卡+U盾+手机卡，支持各大银行，量大从优，长期合作优惠更多。联系TG: @card_seller_888",
    translation: "",
    images: ["/bank-card-fraud-evidence.jpg"],
    publishTime: "2024-12-25 06:15:22",
    channel: "Telegram",
    publisherId: "@card_seller_888",
    sourceUrl: "https://t.me/darkmarket_channel/12345",
    sourceTitle: "暗网市场频道",
    relatedDomain: "amazon.com",
    isNewGang: true,
    isNewContent: true,
    riskScene: "账号盗用",
    riskTags: ["银行卡买卖", "四件套", "身份信息泄露"],
    status: "pending",
  },
  {
    id: "CLU-2024122502",
    captureTime: "2024-12-25 09:15:43",
    customer: "TIKTOKSHOP",
    industry: "电商",
    original: "专业刷单团队，日入500+，无需押金，工资日结。新人培训免费，老手直接上岗。私聊详谈 @shuadan_master",
    translation: "",
    images: [],
    publishTime: "2024-12-25 07:30:11",
    channel: "Discord",
    publisherId: "shuadan_master#1234",
    sourceUrl: "https://discord.gg/abcd1234",
    sourceTitle: "兼职交流群",
    relatedDomain: "tiktok.com",
    isNewGang: false,
    isNewContent: false,
    riskScene: "提供礼品卡交易服务",
    riskTags: ["刷单", "虚假交易", "佣金诈骗"],
    status: "pending",
  },
  {
    id: "CLU-2024122503",
    captureTime: "2024-12-25 10:22:08",
    customer: "SHEIN",
    industry: "电商",
    original:
      "High quality credit card dumps, CVV full info available. Fresh data daily updated. BTC/USDT accepted. Contact: creditking@proton.me",
    translation: "高质量信用卡转储，CVV完整信息可用。每日更新新鲜数据。接受BTC/USDT付款。联系：creditking@proton.me",
    images: ["/credit-card-data-screenshot.jpg", "/payment-proof.jpg"],
    publishTime: "2024-12-25 08:45:30",
    channel: "暗网论坛",
    publisherId: "CreditKing2024",
    sourceUrl: "http://darkforum.onion/thread/98765",
    sourceTitle: "Carding Forum - Premium Section",
    relatedDomain: "shein.com",
    isNewGang: true,
    isNewContent: true,
    riskScene: "信息窃取",
    riskTags: ["信用卡盗刷", "CVV交易", "数据泄露"],
    status: "pending",
  },
  {
    id: "CLU-2024122504",
    captureTime: "2024-12-25 11:08:55",
    customer: "ALIEXPRESS",
    industry: "电商",
    original: "代办车险理赔，无需出险现场，全程线上操作。成功率95%以上，手续费仅收赔付金额10%。微信：fake_claim_888",
    translation: "",
    images: [],
    publishTime: "2024-12-25 09:20:17",
    channel: "微信群",
    publisherId: "fake_claim_888",
    sourceUrl: "",
    sourceTitle: "车友交流群",
    relatedDomain: "aliexpress.com",
    isNewGang: false,
    isNewContent: true,
    riskScene: "虚假交易",
    riskTags: ["保险欺诈", "虚假理赔", "骗保"],
    status: "pending",
  },
  {
    id: "CLU-2024122505",
    captureTime: "2024-12-25 12:35:22",
    customer: "LAZADA",
    industry: "电商",
    original: "收购各银行内部员工数据，客户信息、账户余额等，价格面议。数据越全越新，价格越高。TG: @data_buyer_pro",
    translation: "",
    images: [],
    publishTime: "2024-12-25 10:50:40",
    channel: "Telegram",
    publisherId: "@data_buyer_pro",
    sourceUrl: "https://t.me/data_market/5678",
    sourceTitle: "数据交易频道",
    relatedDomain: "lazada.com",
    isNewGang: true,
    isNewContent: true,
    riskScene: "信息窃取",
    riskTags: ["内部数据", "客户信息", "数据买卖"],
    status: "pending",
  },
  {
    id: "CLU-2024122506",
    captureTime: "2024-12-25 13:18:30",
    customer: "VINTED",
    industry: "电商",
    original: "内幕消息，下周必涨股票，跟着操作稳赚不赔。入群费888，回本后再收20%分成。QQ群：123456789",
    translation: "",
    images: [],
    publishTime: "2024-12-25 11:30:00",
    channel: "QQ群",
    publisherId: "stock_master_666",
    sourceUrl: "",
    sourceTitle: "股票交流群",
    relatedDomain: "vinted.com",
    isNewGang: false,
    isNewContent: true,
    riskScene: "虚假交易",
    riskTags: ["荐股诈骗", "投资诈骗", "虚假信息"],
    status: "pending",
  },
  {
    id: "CLU-2024122507",
    captureTime: "2024-12-25 14:05:12",
    customer: "TIKTOK",
    industry: "社交",
    original: "代下单服务，各大电商平台均可，利用内部优惠券，商品五折起。微信：cheap_buy_888",
    translation: "",
    images: [],
    publishTime: "2024-12-25 12:20:45",
    channel: "微信群",
    publisherId: "cheap_buy_888",
    sourceUrl: "",
    sourceTitle: "省钱购物群",
    relatedDomain: "tiktok.com",
    isNewGang: true,
    isNewContent: false,
    riskScene: "提供礼品卡交易服务",
    riskTags: ["优惠券滥用", "代下单", "薅羊毛"],
    status: "pending",
  },
  {
    id: "CLU-2024122508",
    captureTime: "2024-12-25 15:22:08",
    customer: "ICBU",
    industry: "B2B",
    original: "出售支付通道，费率0.3%起，T+0结算，支持各类业务。长期稳定，欢迎咨询。TG: @payment_channel",
    translation: "",
    images: [],
    publishTime: "2024-12-25 13:45:30",
    channel: "Twitter",
    publisherId: "@loan_service_pro",
    sourceUrl: "https://twitter.com/loan_service_pro/status/123",
    sourceTitle: "贷款服务推广",
    relatedDomain: "alibaba.com",
    isNewGang: false,
    isNewContent: true,
    riskScene: "虚假交易",
    riskTags: ["贷款诈骗", "虚假广告", "非法金融"],
    status: "pending",
  },
  {
    id: "CLU-2024122509",
    captureTime: "2024-12-25 16:10:45",
    customer: "AMAZON",
    industry: "电商",
    original: "代办社保、医保报销，各类发票均可处理。成功率高，价格优惠。微信：insurance_agent_666",
    translation: "",
    images: [],
    publishTime: "2024-12-25 15:20:15",
    channel: "微信群",
    publisherId: "insurance_agent_666",
    sourceUrl: "",
    sourceTitle: "保险理赔群",
    relatedDomain: "amazon.com",
    isNewGang: false,
    isNewContent: false,
    riskScene: "虚假交易",
    riskTags: ["保险欺诈", "发票造假", "骗保"],
    status: "pending",
  },
  {
    id: "CLU-2024122510",
    captureTime: "2024-12-25 17:05:33",
    customer: "TIKTOKSHOP",
    industry: "电商",
    original: "出售支付通道，费率0.3%起，T+0结算，支持各类业务。长期稳定，欢迎咨询。TG: @payment_channel",
    translation: "",
    images: [],
    publishTime: "2024-12-25 14:30:20",
    channel: "Telegram",
    publisherId: "@payment_channel",
    sourceUrl: "https://t.me/payment_services/789",
    sourceTitle: "支付服务频道",
    relatedDomain: "tiktok.com",
    isNewGang: true,
    isNewContent: true,
    riskScene: "资金盗取",
    riskTags: ["非法支付通道", "洗钱", "资金转移"],
    status: "pending",
  },
  {
    id: "CLU-2024122511",
    captureTime: "2024-12-25 18:30:22",
    customer: "SHEIN",
    industry: "电商",
    original: "收购企业对公账户，价格面议，长期合作优先。要求：正规注册公司，账户状态正常。TG: @corp_account_buy",
    translation: "",
    images: [],
    publishTime: "2024-12-25 16:45:10",
    channel: "Telegram",
    publisherId: "@corp_account_buy",
    sourceUrl: "https://t.me/account_market/456",
    sourceTitle: "账户交易频道",
    relatedDomain: "shein.com",
    isNewGang: true,
    isNewContent: true,
    riskScene: "账号盗用",
    riskTags: ["对公账户买卖", "洗钱", "企业账户"],
    status: "pending",
  },
]
